---
project:
  type: website

website:
  title: "My Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
  
format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
