---
project:
  type: website
  output-dir: docs

website:
  title: "My Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
  
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-location: right
